# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tes.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from GUI import searchGui, details
from function import webScrapper

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1001, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(200, 0, 200, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(500, 30))
        self.textEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textEdit.setTabChangesFocus(False)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.btnSearchClick)
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout.setStretch(0, 50)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 50, 1001, 751))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridAnimeList = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridAnimeList.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridAnimeList.setContentsMargins(25, 25, 25, 25)
        self.gridAnimeList.setObjectName("gridAnimeList")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def addAnimeBox(self,MainWindow,anime):
        frameAnime = QtWidgets.QFrame(self.gridLayoutWidget)
        frameAnime.setMaximumSize(QtCore.QSize(450, 150))
        frameAnime.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        frameAnime.setFrameShape(QtWidgets.QFrame.Box)
        frameAnime.setFrameShadow(QtWidgets.QFrame.Raised)
        frameAnime.setLineWidth(5)
        frameAnime.setObjectName(anime.objName)
        gridLayoutWidget_2 = QtWidgets.QWidget(frameAnime)
        gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 451, 151))
        gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        gridAnime = QtWidgets.QGridLayout(gridLayoutWidget_2)
        gridAnime.setContentsMargins(10, 10, 10, 10)
        gridAnime.setHorizontalSpacing(15)
        gridAnime.setObjectName("gridAnime")
        lblstatus = QtWidgets.QLabel(gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lblstatus.sizePolicy().hasHeightForWidth())
        lblstatus.setSizePolicy(sizePolicy)
        lblstatus.setMaximumSize(QtCore.QSize(225, 30))
        lblstatus.setObjectName("lblstatus")
        gridAnime.addWidget(lblstatus, 1, 1, 1, 1)
        lbl_eps = QtWidgets.QLabel(gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lbl_eps.sizePolicy().hasHeightForWidth())
        lbl_eps.setSizePolicy(sizePolicy)
        lbl_eps.setMaximumSize(QtCore.QSize(225, 30))
        lbl_eps.setObjectName("lbl_eps")
        gridAnime.addWidget(lbl_eps, 2, 1, 1, 1)
        lbl_title = QtWidgets.QLabel(gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lbl_title.sizePolicy().hasHeightForWidth())
        lbl_title.setSizePolicy(sizePolicy)
        lbl_title.setMaximumSize(QtCore.QSize(225, 30))
        lbl_title.setObjectName("lbl_title")
        gridAnime.addWidget(lbl_title, 0, 1, 1, 1)
        lbl_img = QtWidgets.QLabel(gridLayoutWidget_2)
        lbl_img.setMaximumSize(QtCore.QSize(90, 125))
        lbl_img.setScaledContents(True)
        lbl_img.setText("")
        lbl_img.setPixmap(QtGui.QPixmap(anime.thumb))
        lbl_img.setObjectName("lbl_img")
        lbl_img.setScaledContents(True)
        gridAnime.addWidget(lbl_img, 0, 0, 3, 1)
        btn_play = QtWidgets.QPushButton(gridLayoutWidget_2, clicked = lambda: self.frameClick(anime))
        btn_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        btn_play.setMaximumSize(QtCore.QSize(50, 180))
        btn_play.setObjectName("btn_play")
        gridAnime.addWidget(btn_play, 0, 2, 3, 1)
        btn_play.setText("PLAY")
        lbl_eps.setText("Episode : "+anime.eps)
        lbl_title.setText(anime.title)
        lblstatus.setText("Status : "+anime.status)
        return frameAnime
        # self.gridAnimeList.addWidget(frameAnime, cord[0], cord[1], cord[2], cord[3])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AniScrap"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Cari Anime"))
        self.pushButton.setText(_translate("MainWindow", "Cari"))

    def frameClick(self,anime):
        print(anime.title)
        self.Details = QtWidgets.QWidget()
        ui = details.Ui_Form()
        ui.setupUi(self.Details, anime)
        self.Details.show()

    def btnSearchClick(self):
        query = self.textEdit.toPlainText()
        self.Search = QtWidgets.QWidget()
        ui = searchGui.Ui_Form()
        ui.setupUi(self.Search)
        ui.updateList(webScrapper.querySearch(query))
        self.Search.show()

    def updateList(self, MainWindow, animes):
        x, y = 0, 0
        for i in range(8):
            try:
                anime = animes[i]
                print(anime.title)
                animeBox = self.addAnimeBox(MainWindow, anime)
                self.gridAnimeList.addWidget(animeBox,x,y,1,1)
                if y == 1:
                    y = 0
                    x += 1
                else:
                    y+=1
            except:
                continue
