# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'History.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        Form.setMinimumSize(QtCore.QSize(640, 480))
        Form.setMaximumSize(QtCore.QSize(640, 480))
        self.list_history = QtWidgets.QListWidget(Form)
        self.list_history.setGeometry(QtCore.QRect(10, 10, 221, 461))
        self.list_history.setObjectName("list_history")
        item = QtWidgets.QListWidgetItem()
        self.list_history.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_history.addItem(item)
        self.lbl_title = QtWidgets.QLabel(Form)
        self.lbl_title.setGeometry(QtCore.QRect(260, 210, 56, 17))
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_episode = QtWidgets.QLabel(Form)
        self.lbl_episode.setGeometry(QtCore.QRect(260, 240, 56, 17))
        self.lbl_episode.setObjectName("lbl_episode")
        self.lbl_status = QtWidgets.QLabel(Form)
        self.lbl_status.setGeometry(QtCore.QRect(260, 300, 56, 17))
        self.lbl_status.setObjectName("lbl_status")
        self.lbl_outTitle = QtWidgets.QLabel(Form)
        self.lbl_outTitle.setGeometry(QtCore.QRect(350, 210, 271, 17))
        self.lbl_outTitle.setText("")
        self.lbl_outTitle.setObjectName("lbl_outTitle")
        self.lbl_outEps = QtWidgets.QLabel(Form)
        self.lbl_outEps.setGeometry(QtCore.QRect(350, 240, 271, 17))
        self.lbl_outEps.setText("")
        self.lbl_outEps.setObjectName("lbl_outEps")
        self.lbl_outStatus = QtWidgets.QLabel(Form)
        self.lbl_outStatus.setGeometry(QtCore.QRect(350, 300, 271, 17))
        self.lbl_outStatus.setText("")
        self.lbl_outStatus.setObjectName("lbl_outStatus")
        self.lbl_outTotalEps = QtWidgets.QLabel(Form)
        self.lbl_outTotalEps.setGeometry(QtCore.QRect(350, 270, 271, 17))
        self.lbl_outTotalEps.setText("")
        self.lbl_outTotalEps.setObjectName("lbl_outTotalEps")
        self.lbl_totalEps = QtWidgets.QLabel(Form)
        self.lbl_totalEps.setGeometry(QtCore.QRect(260, 270, 56, 17))
        self.lbl_totalEps.setObjectName("lbl_totalEps")
        self.lbl_img = QtWidgets.QLabel(Form)
        self.lbl_img.setGeometry(QtCore.QRect(260, 40, 90, 125))
        self.lbl_img.setMaximumSize(QtCore.QSize(90, 125))
        self.lbl_img.setText("")
        self.lbl_img.setPixmap(QtGui.QPixmap("resource/121382.th.jpg"))
        self.lbl_img.setScaledContents(True)
        self.lbl_img.setObjectName("lbl_img")
        self.txt_sinopsis = QtWidgets.QPlainTextEdit(Form)
        self.txt_sinopsis.setGeometry(QtCore.QRect(380, 70, 251, 101))
        self.txt_sinopsis.setObjectName("txt_sinopsis")
        self.lbl_sinopsis = QtWidgets.QLabel(Form)
        self.lbl_sinopsis.setGeometry(QtCore.QRect(380, 30, 111, 17))
        self.lbl_sinopsis.setObjectName("lbl_sinopsis")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(420, 430, 201, 30))
        self.pushButton.setObjectName("pushButton")
        self.lbl_date = QtWidgets.QLabel(Form)
        self.lbl_date.setGeometry(QtCore.QRect(260, 330, 91, 17))
        self.lbl_date.setObjectName("lbl_date")
        self.lbl_outDate = QtWidgets.QLabel(Form)
        self.lbl_outDate.setGeometry(QtCore.QRect(350, 330, 271, 17))
        self.lbl_outDate.setText("")
        self.lbl_outDate.setObjectName("lbl_outDate")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "History"))
        __sortingEnabled = self.list_history.isSortingEnabled()
        self.list_history.setSortingEnabled(False)
        item = self.list_history.item(0)
        item.setText(_translate("Form", "item1"))
        item = self.list_history.item(1)
        item.setText(_translate("Form", "item2"))
        self.list_history.setSortingEnabled(__sortingEnabled)
        self.lbl_title.setText(_translate("Form", "Title"))
        self.lbl_episode.setText(_translate("Form", "Episode"))
        self.lbl_status.setText(_translate("Form", "Status"))
        self.lbl_totalEps.setText(_translate("Form", "Total"))
        self.lbl_sinopsis.setText(_translate("Form", "Sinopsis"))
        self.pushButton.setText(_translate("Form", "Open Anime Page"))
        self.lbl_date.setText(_translate("Form", "Date Watched"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
