# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Alwan Kemal\Documents\Proyek AniScrapper\Aniscrap\Runtime_Config\UI temp\MediaPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 465)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AnoboyImage = QtWidgets.QLabel(Dialog)
        self.AnoboyImage.setGeometry(QtCore.QRect(0, 80, 441, 261))
        self.AnoboyImage.setStyleSheet("background-image:url(:/newPrefix/imagesCopy.png)")
        self.AnoboyImage.setText("")
        self.AnoboyImage.setPixmap(QtGui.QPixmap(":/newPrefix/imagesCopy.png"))
        self.AnoboyImage.setScaledContents(True)
        self.AnoboyImage.setObjectName("AnoboyImage")
        self.LabelMP = QtWidgets.QLabel(Dialog)
        self.LabelMP.setGeometry(QtCore.QRect(0, 20, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LabelMP.setFont(font)
        self.LabelMP.setStyleSheet("color: rgb(0, 0, 127);")
        self.LabelMP.setObjectName("LabelMP")
        self.radioMPV = QtWidgets.QRadioButton(Dialog)
        self.radioMPV.setGeometry(QtCore.QRect(40, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        self.radioMPV.setFont(font)
        self.radioMPV.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioMPV.setObjectName("radioMPV")
        self.radioVLC = QtWidgets.QRadioButton(Dialog)
        self.radioVLC.setGeometry(QtCore.QRect(330, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        self.radioVLC.setFont(font)
        self.radioVLC.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioVLC.setObjectName("radioVLC")
        self.Submit2Button = QtWidgets.QPushButton(Dialog)
        self.Submit2Button.setGeometry(QtCore.QRect(160, 380, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        self.Submit2Button.setFont(font)
        self.Submit2Button.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.Submit2Button.setObjectName("Submit2Button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LabelMP.setText(_translate("Dialog", "  Preferred Media Player :  "))
        self.radioMPV.setText(_translate("Dialog", "MPV"))
        self.radioVLC.setText(_translate("Dialog", "VLC"))
        self.Submit2Button.setText(_translate("Dialog", "Submit"))
import Format_rc
