# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Alwan Kemal\Documents\Proyek AniScrapper\Aniscrap\Runtime_Config\UI temp\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 464)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 441, 171))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image:url(:/newPrefix/LogoAnoboy.png)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/LogoAnoboy.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 150, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 230, 81, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "                     Sign Up"))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
import Login_rc
