# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Alwan Kemal\Documents\Project Python\UI_Aniscrap\Login_Anilist.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 638)
        Dialog.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.labelAnoboy = QtWidgets.QLabel(Dialog)
        self.labelAnoboy.setGeometry(QtCore.QRect(0, 0, 461, 191))
        self.labelAnoboy.setStyleSheet("background-image:url(:/newPrefix/cats-c6511.jpg)")
        self.labelAnoboy.setText("")
        self.labelAnoboy.setPixmap(QtGui.QPixmap(":/newPrefix/cats-c6511.jpg"))
        self.labelAnoboy.setScaledContents(True)
        self.labelAnoboy.setObjectName("labelAnoboy")
        self.label_FirstTime = QtWidgets.QLabel(Dialog)
        self.label_FirstTime.setGeometry(QtCore.QRect(0, 190, 461, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_FirstTime.setFont(font)
        self.label_FirstTime.setStyleSheet("color: rgb(204, 0, 0);")
        self.label_FirstTime.setObjectName("label_FirstTime")
        self.labelMediaP = QtWidgets.QLabel(Dialog)
        self.labelMediaP.setGeometry(QtCore.QRect(0, 270, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(12)
        self.labelMediaP.setFont(font)
        self.labelMediaP.setStyleSheet("color: rgb(255, 85, 0);")
        self.labelMediaP.setObjectName("labelMediaP")
        self.labelTermux = QtWidgets.QLabel(Dialog)
        self.labelTermux.setGeometry(QtCore.QRect(0, 370, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(12)
        self.labelTermux.setFont(font)
        self.labelTermux.setStyleSheet("color: rgb(255, 85, 0);")
        self.labelTermux.setObjectName("labelTermux")
        self.labelLogin = QtWidgets.QLabel(Dialog)
        self.labelLogin.setGeometry(QtCore.QRect(0, 470, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(12)
        self.labelLogin.setFont(font)
        self.labelLogin.setStyleSheet("color: rgb(255, 85, 0);")
        self.labelLogin.setObjectName("labelLogin")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(180, 320, 91, 20))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 420, 91, 20))
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 520, 91, 20))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.ButtonSubmit = QtWidgets.QPushButton(Dialog)
        self.ButtonSubmit.setGeometry(QtCore.QRect(180, 590, 91, 31))
        self.ButtonSubmit.setObjectName("ButtonSubmit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_FirstTime.setText(_translate("Dialog", "      First Time Setup"))
        self.labelMediaP.setText(_translate("Dialog", "                  1. Preferred Media Player :"))
        self.labelTermux.setText(_translate("Dialog", "                 2. Are you Using Termux ?"))
        self.labelLogin.setText(_translate("Dialog", "                         3. Input Token :"))
        self.ButtonSubmit.setText(_translate("Dialog", "Submit"))
import Anoboy_rc
